name: 'Early Access'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DUKE_ARCHIVE: 'run.duke@early-access.jar'
  DUKE_VERSION: '0-ea'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up Java Development Kit'
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17
      - name: 'Bootstrap Duke from sources'
        run: java src/duke.run/Duke.java /bootstrap
      - name: 'Launch Duke''s main program'
        run: java @duke versions
      - name: 'Upload build artifact'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: duke-early-access-modules-${{ env.DUKE_VERSION }}
          path: .duke/modules

  update-early-access-release:
    needs: [ build ]
    if: github.event_name == 'push' && github.repository == 'sormuras/run.duke' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Download build artifact'
        uses: actions/download-artifact@v3
        with:
          name: duke-early-access-modules-${{ env.DUKE_VERSION }}
          path: .duke/modules
      - name: 'Update Early-Access Release'
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_OVERWRITE: true
          JRELEASER_PROJECT_VERSION: ${{ env.DUKE_VERSION }}
        with:
          version: early-access
          setup-java: false
